PUBLIC sgDir_Tmp AS STRING
PUBLIC sgDir_Fls AS STRING
PUBLIC sgDir_Fls1 AS STRING
PUBLIC sgDir_Fls2 AS STRING
PUBLIC sgDir_Img AS STRING
PUBLIC sgDir_Mp3  AS STRING
PUBLIC sgDir_Pub1 AS STRING
PUBLIC sgDir_Pub2 AS STRING
PUBLIC sgFle_Fon AS STRING
PUBLIC nSW_Fls AS INTEGER
PUBLIC sgNom_Loc AS String 
PUBLIC sgWin_Key AS String 
PUBLIC sRuta as String 
PUBLIC bgDB_Cheked AS Boolean 
PRIVATE iErr1 AS INTEGER, iErr2 AS INTEGER
STORE "" TO sgDir_Tmp,sgDir_Fls1,sgDir_Fls2,sgDir_Img,sgDir_Mp3,sgNom_Loc,sgWin_Key
STORE 0 TO nSW_Fls
STORE 0 TO iErr1,iErr2
STORE .f. TO bgDB_Cheked
MOVE WINDOW SCREEN CENTER
ZOOM WINDOW SCREEN MAX
ON ERROR iErr1=1
MKDIR \RockolaUpdate
ON ERROR
SET DEFAULT TO \RockolaUpdate
RELEASE iErr1, iErr2
SET PROCEDURE TO D:\Rockola\ProgMant\utiles.prg ADDITIVE
ON ERROR controlerror(ERROR(), MESSAGE(), MESSAGE(1), PROGRAM(), LINENO())
SET ESCAPE OFF
SET TALK OFF
SET CONSOLE OFF
SET SAFETY OFF
SET DATE DMY
SET RESOURCE OFF
SET CENTURY ON
SET STATUS BAR OFF
SET SYSMENU TO
SET SYSMENU AUTOMATIC
DO FORM D:\Rockola\ProgMant\form_update 
READ EVENTS
ON SHUTDOWN
CLEAR EVENTS
QUIT
